package org.endeavourhealth.hl7transform.mapper.code;

public enum CodeContext {
    HL7_SEX,
    HL7_NAME_TYPE,
    HL7_ADDRESS_TYPE,
    HL7_TELECOM_USE,
    HL7_TELECOM_EQUIPMENT_TYPE,
    HL7_PRIMARY_LANGUAGE,
    HL7_ETHNIC_GROUP,
    HL7_MARITAL_STATUS,
    HL7_RELIGION,
    HL7_PATIENT_CLASS,
    HL7_ACCOUNT_STATUS,
    HL7_PATIENT_TYPE,
    HL7_ADMISSION_TYPE,
    HL7_DISCHARGE_DISPOSITION,
    HL7_DISCHARGED_TO_LOCATION,
    HL7_MESSAGE_TYPE,
    HL7_PATIENT_DEATH_INDICATOR,
    HL7_PATIENT_ID_TYPE_AND_ASSIGNING_AUTH,
    HL7_DOCTOR_ID_TYPE_AND_ASSIGNING_AUTH,
    HL7_ENCOUNTER_ID_TYPE_AND_ASSIGNING_AUTH,
    HL7_LOCATION_FACILITY;
}
