package org.endeavourhealth.hl7transform.mapper.code;

public enum CodeContext {
    HL7_SEX,
    HL7_NAME_TYPE,
    HL7_ADDRESS_TYPE,
    HL7_TELECOM_USE,
    HL7_TELECOM_EQUIPMENT_TYPE,
    HL7_PRIMARY_LANGUAGE,
    HL7_PATIENT_CLASS,
    HL7_ACCOUNT_STATUS,
    HL7_PATIENT_TYPE,
    HL7_ADMISSION_TYPE,
    HL7_DISCHARGE_DISPOSITION,
    HL7_EVENT_TYPE;
}
