
create or replace function helper.get_split_segments
(
	_message_id integer,
	_max_message_id integer default null
)
returns table
(
	message_id integer,
	segment_name text,
	f1 text, 
	f2 text, 
	f3 text, 
	f4 text, 
	f5 text, 
	f6 text, 
	f7 text, 
	f8 text, 
	f9 text, 
	f10 text, 
	f11 text, 
	f12 text, 
	f13 text, 
	f14 text, 
	f15 text, 
	f16 text, 
	f17 text, 
	f18 text, 
	f19 text, 
	f20 text, 
	f21 text, 
	f22 text, 
	f23 text, 
	f24 text, 
	f25 text, 
	f26 text, 
	f27 text, 
	f28 text, 
	f29 text, 
	f30 text, 
	f31 text, 
	f32 text, 
	f33 text, 
	f34 text, 
	f35 text, 
	f36 text, 
	f37 text, 
	f38 text, 
	f39 text, 
	f40 text,
	f41 text, 
	f42 text, 
	f43 text, 
	f44 text, 
	f45 text, 
	f46 text, 
	f47 text, 
	f48 text, 
	f49 text, 
	f50 text,
	f51 text, 
	f52 text
)
as $$
begin

	return query
	select 
		s.message_id,
		split_part(s.segment_text, '|', 1) as segment_name,
		split_part(s.segment_text, '|', 2) as f1,
		split_part(s.segment_text, '|', 3) as f2,
		split_part(s.segment_text, '|', 4) as f3,
		split_part(s.segment_text, '|', 5) as f4,
		split_part(s.segment_text, '|', 6) as f5,
		split_part(s.segment_text, '|', 7) as f6,
		split_part(s.segment_text, '|', 8) as f7,
		split_part(s.segment_text, '|', 9) as f8,
		split_part(s.segment_text, '|', 10) as f9,
		split_part(s.segment_text, '|', 11) as f10,
		split_part(s.segment_text, '|', 12) as f11,
		split_part(s.segment_text, '|', 13) as f12,
		split_part(s.segment_text, '|', 14) as f13,
		split_part(s.segment_text, '|', 15) as f14,
		split_part(s.segment_text, '|', 16) as f15,
		split_part(s.segment_text, '|', 17) as f16,
		split_part(s.segment_text, '|', 18) as f17,
		split_part(s.segment_text, '|', 19) as f18,
		split_part(s.segment_text, '|', 20) as f19,
		split_part(s.segment_text, '|', 21) as f20,
		split_part(s.segment_text, '|', 22) as f21,
		split_part(s.segment_text, '|', 23) as f22,
		split_part(s.segment_text, '|', 24) as f23,
		split_part(s.segment_text, '|', 25) as f24,
		split_part(s.segment_text, '|', 26) as f25,
		split_part(s.segment_text, '|', 27) as f26,
		split_part(s.segment_text, '|', 28) as f27,
		split_part(s.segment_text, '|', 29) as f28,
		split_part(s.segment_text, '|', 30) as f29,
		split_part(s.segment_text, '|', 31) as f30,
		split_part(s.segment_text, '|', 32) as f31,
		split_part(s.segment_text, '|', 33) as f32,
		split_part(s.segment_text, '|', 34) as f33,
		split_part(s.segment_text, '|', 35) as f34,
		split_part(s.segment_text, '|', 36) as f35,
		split_part(s.segment_text, '|', 37) as f36,
		split_part(s.segment_text, '|', 38) as f37,
		split_part(s.segment_text, '|', 39) as f38,
		split_part(s.segment_text, '|', 40) as f39,
		split_part(s.segment_text, '|', 41) as f40,
		split_part(s.segment_text, '|', 42) as f41,
		split_part(s.segment_text, '|', 43) as f42,
		split_part(s.segment_text, '|', 44) as f43,
		split_part(s.segment_text, '|', 45) as f44,
		split_part(s.segment_text, '|', 46) as f45,
		split_part(s.segment_text, '|', 47) as f46,
		split_part(s.segment_text, '|', 48) as f47,
		split_part(s.segment_text, '|', 49) as f48,
		split_part(s.segment_text, '|', 50) as f49,
		split_part(s.segment_text, '|', 51) as f50,
		split_part(s.segment_text, '|', 52) as f51,
		split_part(s.segment_text, '|', 53) as f52
	from helper.get_segments(_message_id, _max_message_id) s;

end;
$$ language plpgsql;