
ALTER TABLE mapping.organisation
ALTER COLUMN organisation_type SET DATA TYPE character varying (10);


ALTER TABLE mapping.organisation_type
ALTER COLUMN organisation_type SET DATA TYPE character varying (10);


INSERT INTO mapping.organisation_type VALUES ('AR', 'Application Service Provider') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('BM', 'Booking Management System (BMS) Call Centre Establishment') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('CN', 'Cancer Network') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('CR', 'Cancer Registry') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('CQ', 'Care Home Headquarters') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('CT', 'Care Trust') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('CC', 'Clinical Commissioning Group (CCG)') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('CL', 'Clinical Network') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('CA', 'Commissioning Support Unit (CSU)') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('JG', 'Court') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('DD', 'Dental Practice') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('ED', 'Education Establishment') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('EA', 'Executive Agency') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('AP', 'Executive Agency Programme') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('GD', 'Government Department') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('GO', 'Government Office Region (GOR)') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('AA', 'Abeyance and Dispersal GP Practice') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('PR', 'GP Practices in England and Wales') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('HA', 'High Level Health Geography') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('JD', 'Immigration Removal Centre') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('PH', 'Independent Sector Healthcare Provider (ISHP)') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('PS', 'Independent Sector Healthcare Provider Site (ISHPS)') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('EL', 'Local Authority') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('LO', 'Local Service Provider (LSP)') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('MH', 'Military Hospital') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('NP', 'National Application Service Provider') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO', 'National Groupings') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('NS', 'NHS Support Agency') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('TR', 'NHS Trust') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('SI', 'NHS Trust Site') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('TS', 'NHS Trust Service') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('NN', 'Non-NHS Organisation') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('NA', 'Northern Ireland Health & Social Care Board') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('NB', 'Northern Ireland Health & Social Care Trust') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('NC', 'Northern Ireland Local Commissioning Group') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('OH', 'Optical Headquarters') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('OA', 'Other Statutory Authority (OSA)') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('PY', 'Pharmacy') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('PX', 'Pharmacy Headquarters') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('JE', 'Police Constabulary') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('JF', 'Police Custody Suite') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('PT', 'Primary Care Trust') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('ID', 'Primary Healthcare Directorate (Isle of Man)') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('PN', 'Prison Health Service') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('EE', 'School') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('JC', 'Secure Children''s Home') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('JB', 'Secure Training Centre (STC)') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('JH', 'Sexual Assault Referral Centre (SARC)') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('SA', 'Special Health Authority (SpHA)') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('WA', 'Welsh Assembly') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('WH', 'Welsh Health Commission') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('LH', 'Welsh Local Health Board') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('JA', 'Young Offenders Institute') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('CO', 'Community') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('CM', 'Community Mental Health Team') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('HP', 'Hospice') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('HO', 'Hospital') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('HD', 'Hospital Department') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('CI', 'Clinic') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('PV', 'Private Clinic') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('SH', 'Strategic Health Authority') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('HU', 'Health Authority (HA)') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('PC', 'Primary Care Organisation') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('BR', 'Branch Surgery') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('OO', 'Out of Hours') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('NH', 'Nursing Home') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('AE', 'Accident & Emergency') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('PCN', 'Primary Care Network') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO209', 'NHS England') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO262', 'Sustainability Transformation Partnership') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO261', 'Strategic Partnership') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO177', 'Prescribing Cost Centre') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO57', 'Foundation Trust') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO218', 'Commissioning Hub') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO72', 'Other Prescribing Cost Centre') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO180', 'Primary Care Trust Site') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO114', 'DMU Site') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO191', 'Special Health Authority Site') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO122', 'Local Authority Site - Legacy') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO31', 'PPA Epact System') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO29', 'Treatment Centre') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO22', 'Level 04 Pct') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO24', 'Nhs Trust Derived') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO123', 'Local Authority Department') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO138', 'Isle Of Man Government Department') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO106', 'Common Service Agency (CSA)') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO140', 'Isle Of Man Government Directorate Site') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO25', 'PCT Derived') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO90', 'Executive Agency Site') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO93', 'Application Service Provider - Legacy') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO149', 'Welsh Local Health Board Site') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO21', 'Level 03 PCT') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO67', 'Specialised Commissioning Group') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO30', 'Research and Development') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO71', 'Privately Owned Entity') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO39', 'Metropolitan District Council') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO134', 'Health Observatory') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO158', 'Non Statutory NHS Organisation') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO38', 'Council') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO89', 'Executive Agency Programme - Department') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO168', 'Other Statutory Authority Site') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO215', 'Hosts Data Managment Integration Centre (DMIC)') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO212', 'Nhs England (region, Local Office) Site') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO220', 'Secure Training Centre') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO214', 'Commissioning Support Unit Site') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO216', 'Data Services For Commissioners Regional Office (DSCRO)') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO136', 'Strategic Health Authority Site') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO217', 'Dscro Site') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO260', 'Young Offender Institution Prescribing Cost Centre') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO251', 'Immigration Removal Centre Prescribing Cost Centre') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO256', 'Secure Children''s Home Prescribing Cost Centre') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO257', 'Secure Training Centre Prescribing Cost Centre') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO273', 'Combined Authority') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO83', 'Residential Institution') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO211', 'Specialised Commissioning Hub') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO94', 'Appliance Contractor') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO232', 'Immigration Removal Centre') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO147', 'LSP Site') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO274', 'Local Health and Care Record Exemplar') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO249', 'Hospice Prescribing Cost Centre') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO148', 'Local Health Board Site') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO35', 'City Council') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO229', 'Non Residential Institution') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO15', 'Registered Under Part 2 Care Standards Act 2000') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO87', 'Walk In Centre') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO34', 'Borough Council') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO36', 'District Council') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO12', 'LA - Inner London') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO80', 'Out of Hours Cost Centre') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO255', 'Public Health Service Prescribing Cost Centre') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO82', 'Prison Prescribing Cost Centre') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO268', 'Medicine Supplier') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO266', 'Extended Access Provider') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO246', 'Care Home/Nursing Home Prescribing Cost Centre') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO222', 'Local Authority Site') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO108', 'Care Trust Site') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO185', 'Regional Office (RO)') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO267', 'Extended Access Hub') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO119', 'Local Authority - Legacy') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO11', 'LA - Metropolitan District') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO37', 'Metropolitan District') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO40', 'Unitary Authority') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO223', 'London Borough') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO33', 'County Council') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO131', 'Government Department Site') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO258', 'Sexual Assault Referral Centre Prescribing Cost Centre') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO247', 'Community Health Service Prescribing Cost Centre') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO252', 'Optometry Service Prescribing Cost Centre') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO270', 'Domiciliary Care') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO99', 'Clinical Commissioning Group Site') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO142', 'Local Health Board') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO109', 'District Health Authority (DHA)') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO111', 'Directly Managed Unit (DMU)') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO171', 'Primary Care Group') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO250', 'Hospital Service Prescribing Cost Centre') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO173', 'Pathology Lab') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO96', 'Branch Surgery') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO101', 'Social Care Site') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO269', 'Care Home') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO259', 'Urgent & Emergency Care Prescribing Cost Centre') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO210', 'NHS England (region, Local Office)') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO167', 'Optical Site') ON CONFLICT DO NOTHING;
INSERT INTO mapping.organisation_type VALUES ('RO65', 'Private Dental Practice') ON CONFLICT DO NOTHING;
